services:
  - type: web
    name: nefisyemekler
    env: python
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
